name: BattleRoyale
version: '${project.version}'
main: me.dalek.battleroyale.Main
api-version: '1.19'
commands:
  revive:
    description: Commande pour tuer un joueur
    usage: /<command>
    aliases: r
  invite:
    description: Permet d'inviter un joueur dans son équipe
    usage: /<command>
    aliases: i
  accept:
    description: Permet d'accepter une demande d'invitation
    usage: /<command>
    aliases: a
  decline:
    description: Permet de décliner les invitations
    usage: /<command>
    aliases: d
  leave:
    description: Permet de quitter une équipe
    usage: /<command>
    aliases: l
  msg:
    description: Commande msg
    usage: /<command>
    permission: op
  help:
    description: Permet de donner les infos sur les commandes
    usage: /<command>
  run:
    description: Permet de lancer la partie
    usage: /<command>
    permission: op
  pause:
    description: Permet de mettre le timer en pause
    usage: /<command>
    permission: op
  start:
    description: Permet de relancer le timer
    usage: /<command>
    permission: op